const icoPresent = {"SHP":"AC","AND":"AD","UAE":"AE","AFG":"AF","ANT":"AG","ALB":"AL","ARM":"AM","ANG":"AO","ARG":"AR","ASA":"AS","AUT":"AT","AUS":"AU","ARU":"AW","AZE":"AZ","BIH":"BA","BAR":"BB","BAN":"BD","BEL":"BE","BOH":"BX","BUR":"BF","BUL":"BG","BRN":"BH","BDI":"BI","BEN":"BJ","BER":"BM","BRU":"BN","BOL":"BO","BRA":"BR","BAH":"BS","BHU":"BT","BOT":"BW","BLR":"BY","BIZ":"BZ","CAN":"CA","COD":"CD","CAF":"CF","CGO":"CG","SUI":"CH","CIV":"CI","COK":"CK","CHI":"CL","CMR":"CM","CHN":"CN","COL":"CO","CRC":"CR","CUB":"CU","CPV":"CV","CYP":"CY","CZE":"CZ","GER":"DE","DJI":"DJ","DEN":"DK","DMA":"DM","DOM":"DO","ALG":"DZ","ECU":"EC","EST":"EE","EGY":"EG","ERI":"ER","ESP":"ES","ETH":"ET","FIN":"FI","FIJ":"FJ","FAI":"FO","FRA":"FR","GAB":"GA","GBR":"GB","GRN":"GD","GEO":"GE","GCI":"GG","GHA":"GH","GAM":"GM","GUI":"GN","GEQ":"GQ","GRE":"GR","GUA":"GT","GUM":"GU","GBS":"GW","GUY":"GY","HKG":"HK","HON":"HN","CRO":"HR","HAI":"HT","HUN":"HU","INA":"ID","IRL":"IE","ISR":"IL","IND":"IN","IRQ":"IQ","IRI":"IR","ISL":"IS","ITA":"IT","JCI":"JE","JAM":"JM","JOR":"JO","JPN":"JP","KEN":"KE","KGZ":"KG","CAM":"KH","KIR":"KI","COM":"KM","SKN":"KN","PRK":"KP","KOR":"KR","KUW":"KW","CAY":"KY","KAZ":"KZ","LAO":"LA","LIB":"LB","LCA":"LC","LIE":"LI","SRI":"LK","LBR":"LR","LES":"LS","LTU":"LT","LUX":"LU","LAT":"LV","LBA":"LY","MAR":"MA","MON":"MC","MDA":"MD","MNE":"ME","MAD":"MG","MHL":"MH","MKD":"MK","MLI":"ML","MYA":"MM","MGL":"MN","MAC":"MO","MTN":"MR","MLT":"MT","MRI":"MU","MDV":"MV","MAW":"MW","MEX":"MX","MAS":"MY","MOZ":"MZ","NAM":"NA","NIG":"NE","NGR":"NG","NCA":"NI","NED":"NL","NOR":"NO","NEP":"NP","NRU":"NR","NZL":"NZ","OMA":"OM","PAN":"PA","PER":"PE","PNG":"PG","PHI":"PH","PAK":"PK","POL":"PL","PUR":"PR","PLE":"PS","POR":"PT","PLW":"PW","PAR":"PY","QAT":"QA","ROU":"RO","SRB":"RS","RUS":"RU","URS":"RU","RWA":"RW","KSA":"SA","SOL":"SB","SEY":"SC","SUD":"SD","SWE":"SE","SIN":"SG","SLO":"SI","SVK":"SK","SLE":"SL","SMR":"SM","SEN":"SN","SOM":"SO","SUR":"SR","STP":"ST","ESA":"SV","SYR":"SY","SWZ":"SZ","CHA":"TD","TCH":"CZ","TOG":"TG","THA":"TH","TJK":"TJ","TLS":"TL","TKM":"TM","TUN":"TN","TGA":"TO","TUR":"TR","TRI":"TT","TUV":"TV","TPE":"TW","TAN":"TZ","UKR":"UA","UGA":"UG","USA":"US","URU":"UY","UZB":"UZ","VIN":"VC","VEN":"VE","ISV":"VG","VIE":"VN","VAN":"VU","SAM":"WS","YEM":"YE","RSA":"ZA","ZAM":"ZM","ZIM":"ZW"}

const icoPast = {}

const ico = {...icoPresent, icoPast}

const countryConverter = code => ico[code] ? ico[code].toLowerCase() : null

export default countryConverter

